{{- include "anvilkit-agent-background-worker.require" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anvilkit-agent-background-worker.fullname" . }}
  labels:
    {{- include "anvilkit-agent-background-worker.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- include "anvilkit-agent-background-worker.config" . | nindent 4 }}
